[project]
name = "agtech-risk-detector"
version = "0.1.0"
description = "Prototipo Streamlit para evaluación de riesgo agrícola"
authors = ["Diego Molestina"]
dependencies = [
  "streamlit>=1.27.0",
  "pandas>=2.0.0",
  "folium>=0.14.0",
  "streamlit-folium>=0.14.0",
  "requests>=2.28.0",
  "python-dotenv>=1.0.0"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
